### ISSUE TITLE
Undefined Index's

### ISSUE THREAD

**Issue by graph-io** [billerickson/display-posts-shortcode#100] opened 2015-10-15 21:53 UTC
Hi Bill,
Love this thing. I have a non-serious issue but none the less am trying to learn and can't figure out how to qwell this notice I'm receiving. I'm customizing in my functions.php to display an icon based on the value of a custom field. I'll post the code in a gist below but essentially every one of the if statements in this code cause the notice to appear and (when debug is enabled) only display the notice and no results. I have tried adding an !isset into the code but cant seem to get it correct. Would you mind lending a hand?
----------------------------------------------------

<script src="https://gist.github.com/graph-io/866c2fb94890c4a683d5.js"></script>

https://gist.github.com/graph-io/866c2fb94890c4a683d5#file-function-be_display_posts_classes-txt

Help is much appreciated!

**Comment by billerickson** [comment] 2015-10-15 21:58
Duplicate of #99

**Closed by billerickson** 2015-10-15 21:58 UTC
